pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Express App') {
            steps {
                dir('frontend') {
                    sh 'pm2 restart express-app || pm2 start app.js --name express-app'
                }
            }
        }
    }
}
