pipeline {
    agent any

    tools {
        nodejs 'NodeJS-18' 
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Express App') {
            steps {
                sh 'pm2 restart express-app || pm2 start frontend/app.js --name express-app'
            }
        }
    }
}
