services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: express
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:5000 
    volumes:
      - ./frontend:/app   
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
