pipeline {
    agent any

    environment {
        MONGODB_URI = credentials('MONGODB_URI')
        SECRET_KEY = credentials('SECRET_KEY')
    }

    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/floo69/form-docker.git'
            }
        }

        stage('Install Python Deps') {
            steps {
                dir('backend') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Create .env') {
            steps {
                dir('backend') {
                    writeFile file: '.env', text: """
                    MONGO_URI=${MONGO_URI}
                    SECRET_KEY=${SECRET_KEY}
                    """
                }
            }
        }

        stage('Run Flask') {
            steps {
                sh 'pm2 restart flask-app || pm2 start backend/app.py --interpreter python3 --name flask-app'
            }
        }
    }
}
