pipeline {
    agent any

    environment {
        MONGODB_URI = credentials('MONGODB_URI')
    }

    stages {
        stage('Install Python Deps') {
            steps {
                dir('backend') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Create .env File') {
            steps {
                dir('backend') {
                    writeFile file: '.env', text: """
                    MONGODB_URI=${MONGODB_URI}
                    """
                }
            }
        }

        stage('Run Flask') {
            steps {
                sh 'pm2 restart flask-app || pm2 start backend/app.py --interpreter python3 --name flask-app'
            }
        }
    }
}
